{
 "title": "Crypto Exporter",
 "description": "Simple dashboard for crypto-exporter",
 "tags": [
  "prometheus",
  "cryptocurrency",
  "exchange"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "exchange",
    "query": "label_values(crypto_order_count, exchange_name)"
   },
   {
    "name": "base_currency",
    "query": "label_values(crypto_order_count, base_currency)"
   },
   {
    "name": "quote_currency",
    "query": "label_values(crypto_order_count, quote_currency)"
   },
   { "name": "summary_period", "query": "1h,3h,6h,12h,24h" }
  ]
 },
 "panels": [
  { "title": "Summary ($exchange)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "exchange" },
  {
   "title": "Last Bid ($base_currency)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "crypto_trade_price{exchange_name=~\"^$exchange$\", base_currency=\"$base_currency\", quote_currency=\"$quote_currency\", operation=\"bid\"}"
    }
   ]
  },
  {
   "title": "High ($base_currency)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(crypto_trade_price{exchange_name=~\"^$exchange$\", base_currency=\"$base_currency\", quote_currency=\"$quote_currency\"}[$summary_period]))"
    }
   ]
  },
  {
   "title": "Price Variation ($base_currency - $quote_currency)",
   "type": "singlestat",
   "description": "Difference in price between the minimum price at the period start and the maximum price at period end.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(max(crypto_trade_price{exchange_name=~\"^$exchange$\", base_currency=\"$base_currency\", quote_currency=\"$quote_currency\"}) - min(crypto_trade_price{exchange_name=~\"^$exchange$\", base_currency=\"$base_currency\", quote_currency=\"$quote_currency\"} offset $summary_period))\n/\nmin(crypto_trade_price{exchange_name=~\"^$exchange$\", base_currency=\"$base_currency\", quote_currency=\"$quote_currency\"} offset $summary_period)"
    }
   ]
  },
  {
   "title": "Volume ($base_currency - $quote_currency)",
   "type": "singlestat",
   "description": "Total number of coins exchanged in the selected period.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(crypto_trade_amount_sum{exchange_name=~\"^$exchange$\", base_currency=\"$base_currency\"}[$summary_period]))"
    }
   ]
  },
  {
   "title": "Last Ask ($base_currency)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "crypto_trade_price{exchange_name=~\"^$exchange$\", base_currency=\"$base_currency\", quote_currency=\"$quote_currency\", operation=\"ask\"}"
    }
   ]
  },
  {
   "title": "Low ($base_currency)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(min_over_time(crypto_trade_price{exchange_name=~\"^$exchange$\", base_currency=\"$base_currency\", quote_currency=\"$quote_currency\"}[$summary_period]))"
    }
   ]
  },
  { "title": "Order Book", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Bids vs Asks ($base_currency)",
   "type": "graph",
   "description": "Number of bid/asks orders created in the last minute, across all selected exchanges.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "op/m" }
   ],
   "targets": [
    {
     "expr": "sum(increase(crypto_order_count{exchange_name=~\"^$exchange$\", base_currency=\"$base_currency\", quote_currency=\"$quote_currency\", event=\"create\"}[1m])) by (operation)",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "Bid Orders ($base_currency)",
   "type": "graph",
   "description": "Number of bid orders created (or canceled) in the last minute.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "op/m" }
   ],
   "targets": [
    {
     "expr": "sum(increase(crypto_order_count{exchange_name=~\"^$exchange$\", base_currency=\"$base_currency\", quote_currency=\"$quote_currency\", operation=\"bid\"}[1m])) by (event, exchange_name)",
     "legendFormat": "{{ event }} ({{ exchange_name }})"
    }
   ]
  },
  {
   "title": "Ask Orders ($base_currency)",
   "type": "graph",
   "description": "Number of ask orders created (or canceled) in the last minute.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "op/m" }
   ],
   "targets": [
    {
     "expr": "sum(increase(crypto_order_count{exchange_name=~\"^$exchange$\", base_currency=\"$base_currency\", quote_currency=\"$quote_currency\", operation=\"ask\"}[1m])) by (event, exchange_name)",
     "legendFormat": "{{ event }} ({{ exchange_name }})"
    }
   ]
  },
  { "title": "Trades", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Trade Operations ($base_currency)",
   "type": "graph",
   "description": "Number of trades (bids/asks) per minute.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "trade/m" }
   ],
   "targets": [
    {
     "expr": "sum(increase(crypto_trade_count{exchange_name=~\"^$exchange$\", base_currency=\"$base_currency\", quote_currency=\"$quote_currency\"}[1m])) by (operation, exchange_name)",
     "legendFormat": "{{ operation }} ({{ exchange_name }})"
    }
   ]
  },
  {
   "title": "Trade Unit Prices ($base_currency - $quote_currency)",
   "type": "graph",
   "description": "Current unit price, in $base_currency.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "unit price" }
   ],
   "targets": [
    {
     "expr": "sum(crypto_trade_price{exchange_name=~\"^$exchange$\", base_currency=\"$base_currency\", quote_currency=\"$quote_currency\"}) by (operation, exchange_name)",
     "legendFormat": "{{ operation }} ({{ exchange_name }})"
    }
   ]
  },
  {
   "title": "Volume ($base_currency)",
   "type": "graph",
   "description": "Volume exchanged, in $base_currency, within the last minute.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "amount" }
   ],
   "targets": [
    {
     "expr": "sum(increase(crypto_trade_amount_sum{exchange_name=~\"^$exchange$\", base_currency=\"$base_currency\", quote_currency=\"$quote_currency\"}[1m])) by (operation, exchange_name)",
     "legendFormat": "{{ operation }} ({{ exchange_name }})"
    }
   ]
  }
 ]
}